import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1790353961289 implements MigrationInterface {
    name = 'InitialSchema1790353961289'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "name" character varying(100) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "name" character varying(100) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."files_status_enum" AS ENUM('pending', 'processing', 'ready', 'failed')`);
        await queryRunner.query(`CREATE TABLE "files" ("id" uuid NOT NULL, "owner_id" uuid, "name" character varying(255) NOT NULL, "type" character varying(127) NOT NULL, "size" bigint NOT NULL, "status" "public"."files_status_enum" NOT NULL DEFAULT 'ready', "key" character varying(1024) NOT NULL, "optimized_key" character varying(1024), "thumbnail_key" character varying(1024), "medium_key" character varying(1024), "width" integer, "height" integer, "blurhash" character varying(100), "duration" double precision, "waveform" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_FILES_STATUS_CREATED" ON "files"  ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_FILES_OWNER" ON "files"  ("owner_id") `);
        await queryRunner.query(`CREATE TABLE "profiles" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "first_name" character varying(40), "last_name" character varying(40), "birth_date" date, "gender" character varying(20), "locale" character varying(10), "last_online" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "avatar_id" uuid, CONSTRAINT "REL_9e432b7df0d182f8d292902d1a" UNIQUE ("user_id"), CONSTRAINT "PK_8e520eb4da7dc01d0e190447c8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_PROFILES_LAST_ONLINE" ON "profiles"  ("last_online") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_PROFILES_USER_ID" ON "profiles"  ("user_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "email" character varying(50), "email_verified" boolean NOT NULL DEFAULT false, "phone" character varying(14), "username" character varying(32), "password_hash" text NOT NULL, "two_factor_hash" text, "two_factor_hint" character varying(100), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_USERS_USERNAME" ON "users"  ("username") WHERE username IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_USERS_PHONE" ON "users"  ("phone") WHERE phone IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_USERS_EMAIL" ON "users"  ("email") WHERE email IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "api_keys" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "name" character varying(100) NOT NULL, "prefix" character varying(8) NOT NULL, "hash" character varying(64) NOT NULL, "scopes" character varying(100) array NOT NULL DEFAULT '{}', "owner_id" uuid NOT NULL, "last_used_at" TIMESTAMP WITH TIME ZONE, "expires_at" TIMESTAMP WITH TIME ZONE, "revoked_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_API_KEYS_OWNER" ON "api_keys"  ("owner_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_API_KEYS_PREFIX" ON "api_keys"  ("prefix") `);
        await queryRunner.query(`CREATE TABLE "audit_events" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "type" character varying(64) NOT NULL, "actor_id" uuid, "subject_id" character varying(255), "ip" character varying(45), "user_agent" character varying(500), "meta" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_910f64d901a5c3e9878f0d4a407" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_AUDIT_EVENTS_CREATED_AT" ON "audit_events"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUDIT_EVENTS_TYPE_CREATED" ON "audit_events"  ("type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUDIT_EVENTS_ACTOR_CREATED" ON "audit_events"  ("actor_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "reset_password_tokens" ("user_id" uuid NOT NULL, "token_hash" character varying(64) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "issued_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_edc35c140e0051cc6b96cac130c" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_RESET_TOKENS_TOKEN_HASH" ON "reset_password_tokens"  ("token_hash") `);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "refresh_token_hash" character varying(64) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "device_name" character varying(200), "device_type" character varying(50), "ip" character varying(45), "user_agent" character varying(500), "last_active_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_SESSIONS_EXPIRES_AT" ON "sessions"  ("expires_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_SESSIONS_REFRESH_TOKEN_HASH" ON "sessions"  ("refresh_token_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_SESSIONS_USER" ON "sessions"  ("user_id") `);
        await queryRunner.query(`CREATE TABLE "email_change_requests" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "new_email" character varying(50) NOT NULL, "code_hash" character varying(64) NOT NULL, "attempts" integer NOT NULL DEFAULT '0', "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_bd4c3add2b94c4ee2207d9234d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_EMAIL_CHANGE_REQUESTS_USER" ON "email_change_requests"  ("user_id") `);
        await queryRunner.query(`CREATE TABLE "otp" ("user_id" uuid NOT NULL, "code" character varying(6) NOT NULL, "expire_at" TIMESTAMP WITH TIME ZONE NOT NULL, "attempts" integer NOT NULL DEFAULT '0', "sent_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_258d028d322ea3b856bf9f12f25" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."privacy_settings_show_last_online_enum" AS ENUM('everyone', 'contacts', 'nobody')`);
        await queryRunner.query(`CREATE TYPE "public"."privacy_settings_show_phone_enum" AS ENUM('everyone', 'contacts', 'nobody')`);
        await queryRunner.query(`CREATE TYPE "public"."privacy_settings_show_avatar_enum" AS ENUM('everyone', 'contacts', 'nobody')`);
        await queryRunner.query(`CREATE TABLE "privacy_settings" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "show_last_online" "public"."privacy_settings_show_last_online_enum" NOT NULL DEFAULT 'everyone', "show_phone" "public"."privacy_settings_show_phone_enum" NOT NULL DEFAULT 'contacts', "show_avatar" "public"."privacy_settings_show_avatar_enum" NOT NULL DEFAULT 'everyone', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_626e170465665a6a6e9831bb153" UNIQUE ("user_id"), CONSTRAINT "REL_626e170465665a6a6e9831bb15" UNIQUE ("user_id"), CONSTRAINT "PK_e31cc479f8c3267c86511223ea0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_PRIVACY_USER" ON "privacy_settings"  ("user_id") `);
        await queryRunner.query(`CREATE TABLE "biometrics" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "device_id" character varying(100) NOT NULL, "public_key" text NOT NULL, "device_name" character varying(100), "challenge" character varying(64), "challenge_expires_at" TIMESTAMP WITH TIME ZONE, "last_used_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c70c2bb84b5580ee9beff6daed4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_BIOMETRICS_USER_DEVICE" ON "biometrics"  ("user_id", "device_id") `);
        await queryRunner.query(`CREATE TABLE "passkeys" ("id" character varying NOT NULL, "public_key" bytea NOT NULL, "user_id" uuid NOT NULL, "counter" integer NOT NULL, "device_type" character varying NOT NULL DEFAULT 'singleDevice', "transports" jsonb, "last_used" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_db928e6fd79e7098911268a74c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_PASSKEYS_USER_ID" ON "passkeys"  ("user_id") `);
        await queryRunner.query(`CREATE TABLE "passkey_challenges" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "challenge" character varying NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6e53152b7ac3d0c599f2cffdd7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_PASSKEY_CHALLENGES_USER" ON "passkey_challenges"  ("user_id") `);
        await queryRunner.query(`CREATE TABLE "job_runs" ("id" uuid NOT NULL, "queue" character varying(100) NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'queued', "title" character varying(200) NOT NULL, "progress" real NOT NULL DEFAULT '0', "progress_text" character varying(200), "log_tail" jsonb NOT NULL DEFAULT '[]', "result" jsonb, "error" jsonb, "owner_id" uuid, "scope_type" character varying(50), "scope_id" character varying(100), "attempt" integer NOT NULL DEFAULT '0', "cancel_requested" boolean NOT NULL DEFAULT false, "lease_until" TIMESTAMP WITH TIME ZONE, "files" jsonb, "started_at" TIMESTAMP WITH TIME ZONE, "finished_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4d0012c04fcfc287550b76be7e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_JOB_RUNS_STATUS_LEASE" ON "job_runs"  ("status", "lease_until") `);
        await queryRunner.query(`CREATE INDEX "IDX_JOB_RUNS_SCOPE_CREATED" ON "job_runs"  ("scope_type", "scope_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_JOB_RUNS_OWNER_CREATED" ON "job_runs"  ("owner_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions"  ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions"  ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles"  ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles"  ("role_id") `);
        await queryRunner.query(`CREATE TABLE "user_permissions" ("user_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_a537c48b1f80e8626a71cb56589" PRIMARY KEY ("user_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3495bd31f1862d02931e8e8d2e" ON "user_permissions"  ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8145f5fadacd311693c15e41f1" ON "user_permissions"  ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_4bc1db1f4f34ec9415acd88afdb" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "FK_9e432b7df0d182f8d292902d1a2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "FK_768e6771e0ced8d2993a088b2f3" FOREIGN KEY ("avatar_id") REFERENCES "files"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_d93cc0e04cac89126b2155ba9bc" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reset_password_tokens" ADD CONSTRAINT "FK_edc35c140e0051cc6b96cac130c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_change_requests" ADD CONSTRAINT "FK_45b3391d341b1a58def2881e8c2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "otp" ADD CONSTRAINT "FK_258d028d322ea3b856bf9f12f25" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "privacy_settings" ADD CONSTRAINT "FK_626e170465665a6a6e9831bb153" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "biometrics" ADD CONSTRAINT "FK_d9ba3c152902f504cb6f1c0481f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passkeys" ADD CONSTRAINT "FK_02227b9a8a34a808e3e23800b00" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_permissions" ADD CONSTRAINT "FK_3495bd31f1862d02931e8e8d2e8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_permissions" ADD CONSTRAINT "FK_8145f5fadacd311693c15e41f10" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_permissions" DROP CONSTRAINT "FK_8145f5fadacd311693c15e41f10"`);
        await queryRunner.query(`ALTER TABLE "user_permissions" DROP CONSTRAINT "FK_3495bd31f1862d02931e8e8d2e8"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "passkeys" DROP CONSTRAINT "FK_02227b9a8a34a808e3e23800b00"`);
        await queryRunner.query(`ALTER TABLE "biometrics" DROP CONSTRAINT "FK_d9ba3c152902f504cb6f1c0481f"`);
        await queryRunner.query(`ALTER TABLE "privacy_settings" DROP CONSTRAINT "FK_626e170465665a6a6e9831bb153"`);
        await queryRunner.query(`ALTER TABLE "otp" DROP CONSTRAINT "FK_258d028d322ea3b856bf9f12f25"`);
        await queryRunner.query(`ALTER TABLE "email_change_requests" DROP CONSTRAINT "FK_45b3391d341b1a58def2881e8c2"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`ALTER TABLE "reset_password_tokens" DROP CONSTRAINT "FK_edc35c140e0051cc6b96cac130c"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_d93cc0e04cac89126b2155ba9bc"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "FK_768e6771e0ced8d2993a088b2f3"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "FK_9e432b7df0d182f8d292902d1a2"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_4bc1db1f4f34ec9415acd88afdb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8145f5fadacd311693c15e41f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3495bd31f1862d02931e8e8d2e"`);
        await queryRunner.query(`DROP TABLE "user_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_JOB_RUNS_OWNER_CREATED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_JOB_RUNS_SCOPE_CREATED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_JOB_RUNS_STATUS_LEASE"`);
        await queryRunner.query(`DROP TABLE "job_runs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PASSKEY_CHALLENGES_USER"`);
        await queryRunner.query(`DROP TABLE "passkey_challenges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PASSKEYS_USER_ID"`);
        await queryRunner.query(`DROP TABLE "passkeys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BIOMETRICS_USER_DEVICE"`);
        await queryRunner.query(`DROP TABLE "biometrics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PRIVACY_USER"`);
        await queryRunner.query(`DROP TABLE "privacy_settings"`);
        await queryRunner.query(`DROP TYPE "public"."privacy_settings_show_avatar_enum"`);
        await queryRunner.query(`DROP TYPE "public"."privacy_settings_show_phone_enum"`);
        await queryRunner.query(`DROP TYPE "public"."privacy_settings_show_last_online_enum"`);
        await queryRunner.query(`DROP TABLE "otp"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EMAIL_CHANGE_REQUESTS_USER"`);
        await queryRunner.query(`DROP TABLE "email_change_requests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SESSIONS_USER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SESSIONS_REFRESH_TOKEN_HASH"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SESSIONS_EXPIRES_AT"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_RESET_TOKENS_TOKEN_HASH"`);
        await queryRunner.query(`DROP TABLE "reset_password_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUDIT_EVENTS_ACTOR_CREATED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUDIT_EVENTS_TYPE_CREATED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUDIT_EVENTS_CREATED_AT"`);
        await queryRunner.query(`DROP TABLE "audit_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_API_KEYS_PREFIX"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_API_KEYS_OWNER"`);
        await queryRunner.query(`DROP TABLE "api_keys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USERS_EMAIL"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USERS_PHONE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USERS_USERNAME"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PROFILES_USER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PROFILES_LAST_ONLINE"`);
        await queryRunner.query(`DROP TABLE "profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILES_OWNER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILES_STATUS_CREATED"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP TYPE "public"."files_status_enum"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "roles"`);
    }

}
